options:
  rabbit-user:
    default: neutron
    type: string
    description: Username used to access RabbitMQ queue
  rabbit-vhost:
    default: openstack
    type: string
    description: RabbitMQ vhost
  use-syslog:
    type: boolean
    default: False
    description: |
      By default, all services will log into their corresponding log files.
      Setting this to True will force all services to log to the syslog.
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  enable-ipv6:
    default: False
    type: boolean
    description: |
      Enable Calico's IPv6 support. Requires that all nodes with this
      charm installed on them have global scope IPv6 addresses.
